sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t 2002tony/docker-react-app -f docker-react-app/Dockerfile.dev .

script:
  - docker run -e CI=true 2002tony/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"
